name: Comment via action

on:
  issues:
    types: [ opened ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 3 
          body: |
            Thank you for submitting an issue. Our team will review, triage, and respond to issues as we are able. 
            As a reminder, if you're reporting a bug, please include as much detail as you can, including things like:
            * the result or output you expected to receive
            * the result or output that you did receive
            * the version(s) you are running
            * the exact steps you took that led to this outcome (including any code, if applicable)
