name: Comment on new PR
on:
  pull_request: 
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repository! Thank you for your proposed contribution to this project."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
